openapi: 3.0.0
info:
  version: 1.0.0
  title: TrustedForm Check-In API
  termsOfService: 'https://activeprospect.com/trustedform-eula'
  description: |
    # Overview
    ActiveProspect provides the TrustedForm Check-In API to enable TrustedForm non-client vendors to extend the claim period of certificates for lead buyers who want to claim TrustedForm certificates beyond the standard claim period.

    ## Claim Period
    The "claim period" is the timeframe within which a TrustedForm Certificate is issued and must be claimed or extended by a TrustedForm Account holder, else it will expire. 

    * The standard claim period is approximately 72 hours (3 days). 
    * The extended claim period is approximately 2,400 hours (3 months). 

    Within the claim period, TrustedForm Certificates are visible to anyone with access to the TrustedForm Certificate URL. After this period, only claimed TrustedForm Certificates are accessible by the TrustedForm account holders that claimed them.

    ## When to extend the claim period
    Lead buyers want to claim TrustedForm certificates but can't because the certificates have exceeded the standard claim period (72 hours old) and have expired. Common use cases include call center qualified leads and aged leads. For these situations ActiveProspect provides this API to switch certificates to the extended claim period (3 months).

    ## Prerequisites
    * [Add the TrustedForm script](https://activeprospect.com/products/trustedform-for-publishers/) to your lead forms.
    * [Sign up for an ActiveProspect account](https://sso.activeprospect.com/registration/new?product=extend) to receive an API Key.
    

    ## Authentication
    <security-definitions /> 
    * The ActiveProspect API Key is available at [My Account](https://sso.activeprospect.com/account) > Account Settings

  contact:
    name: ActiveProspect Support Team
    email: support@activeprospect.com
    url: https://support.activeprospect.com
  x-logo:
    url: https://mrjuicebox.github.io/ActiveProspect_Full.svg
    altText: ActiveProspect Inc.
externalDocs:
  description: TrustedForm Knowledge Base
  url: https://support.activeprospect.com/hc/en-us/categories/200128909-TrustedForm

# tags:
#   - name: check_in
#     description: Operations that can be performed against the Check-In API
# x-tagGroups:
#   - name: Check-In Operations
#     tags:
#       - check_in
paths:
  '{certificate_id}/check_in':
    post:
      summary: Check-In
      description: |
        Check-In supports various actions for a TrustedForm Certificate (e.g. extending the claim period on certificates).
        
        Failing to make the authenticated API call within the [standard claim period](https://support.activeprospect.com/hc/en-us/articles/204744025) (72 hours of generating the lead) will result in the irretrievable deletion of the certificate.

      tags:
        - General
      operationId: check_in
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckInResponse'
        '400':
          description: Malformed Certificate URL
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckIn'
        required: true
      servers:
        - url: https://cert.trustedform.com/
      security:
        - API Key: []
      x-code-samples:
        - lang: 'curl'
          source: |
            API_KEY="f3bff7c5140a10ab5ff2e628f433f0bb51d255d1a"
            CERTIFICATE_ID="1f1b96c9150d8050e858c043d543bb4eadae0e6f"
            curl --user "API:$API_KEY" \
                 --header "Accept: application/json" \
                 --request POST \
                 --data '{"extend": true}' \
                 https://cert.trustedform.com/$CERTIFICATE_ID/check_in

components:
  schemas:
    CheckIn:
      type: object
      properties:
        extend:
          description: Extend Certificate
          type: boolean
          default: true
    CheckInResponse:
      description: An HTTP status code generated from a certificate URL.

  securitySchemes:
    API Key:
      scheme: basic
      description: >
        TrustedForm uses [HTTP Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) with the username `API` and your API key as the password.
        For example: `API:1f1b96c9150d8050e858c043d543bb4eadae0e6f`
      type: http
