openapi: 3.0.0
info:
  version: 1.0.0
  title: TrustedForm Check-In API
  termsOfService: 'https://activeprospect.com/trustedform-eula'
  description: |
    # Overview
    ActiveProspect provides the TrustedForm Check-In API to enable TrustedForm non-client vendors to extend the claim period of certificates for lead buyers who want to claim TrustedForm certificates beyond the standard claim period.

    ## Claim Period
    The "claim period" is the timeframe within which a TrustedForm Certificate is issued and must be claimed or extended by a TrustedForm Account holder, else it will expire. 

    * The standard claim period is approximately 72 hours. 
    * The extended claim period is approximately 2,400 hours. 

    Within the claim period, TrustedForm Certificates are visible to anyone with access to the TrustedForm Certificate URL. After this period, only claimed TrustedForm Certificates are accessible by the TrustedForm account holders that claimed them.

    ## When to extend the claim period
    There are situations where lead buyers need to claim a certificate that is more than 72 hours old. The two primary use cases are: 1) call center qualified leads, and 2) aged leads. For these situations ActiveProspect provides this API to extend the claim period to 90 days. 

    ## Extending the claim period
    Extending the claim period requires the following actions:
    * [Add the TrustedForm script](https://activeprospect.com/products/trustedform-for-publishers/) to your lead forms.
    * [Sign up for an ActiveProspect account](https://sso.activeprospect.com/registration/new?product=extend) to receive an API Key.
    * Make an authenticated API call within the initial 72 hour claim period as documented below.

    ### Important Notes
    * The ActiveProspect API Key is available at [My Account](https://sso.activeprospect.com/account) > Account Settings
    * Failing to make the authenticated API call within 72 hours of generating the lead will result in the irretrievable deletion of the certificate. Lead buyers relying on TrustedForm to verify and document consent for compliance with regulations like TCPA, CASL, etc. are unlikely to purchase leads without a valid TrustedForm Certificate.
    * For vendors with an ActiveProspect Account who are TrustedForm clients, **you do not need a separate action to extend certificates**. Claiming your certificates already extends the claim period as long as your account is [enabled for extended claim](https://app.trustedform.com/#settings).

    <security-definitions /> 

  contact:
    name: ActiveProspect Support Team
    email: support@activeprospect.com
    url: https://support.activeprospect.com
  x-logo:
    url: https://activeprospect.com/wp-content/themes/activeprospect/assets/images/activeprospect-logo.svg
    altText: ActiveProspect logo
externalDocs:
  description: TrustedForm Knowledge Base
  url: https://support.activeprospect.com/hc/en-us/categories/200128909-TrustedForm

# tags:
#   - name: check_in
#     description: Operations that can be performed against the Check-In API
# x-tagGroups:
#   - name: Check-In Operations
#     tags:
#       - check_in
paths:
  '/{cert_id}/check_in':
    post:
      summary: Check-In
      description: |
        Extending a certificate switches it from the Standard claim period (approximately 72 hours) to the Extended claim period (approximately 2,400 hours).

        Append `/check_in` to the certificate URL and perform an authenticated `POST`, including a JSON-encoded object, where one of the constituent keys is `extend` with the boolean value `true`, e.g. `{"extend": true}`.

        The [standard 72 hour claim period](https://support.activeprospect.com/hc/en-us/articles/204744025-Are-TrustedForm-certificates-available-indefinitely-) still applies.
      tags:
        - Check-In URL Operations
      operationId: check_in
      parameters:
        - name: cert_id
          in: path
          description: Certificate ID
          required: true
          deprecated: false
          schema:
            type: string
      responses:
        '200':
          description: Check-In Data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckInResponse'
        '400':
          description: Malformed Certificate URL
        '401':
          description: Unauthorized
        '404':
          description: Certificate Not Found
      servers:
        - url: https://cert.trustedform.com
      security:
        - API Key: []
      x-code-samples:
        - lang: 'curl'
          source: |
            API_KEY="f3bff7c5140a10ab5ff2e628f433f0bb51d255d1a"
            CERT_ID="1f1b96c9150d8050e858c043d543bb4eadae0e6f"
            curl --user "API:$API_KEY" \
                 --header "Accept: application/json" \
                 --request POST \
                 --data '{"extend": true}' \
                 https://cert.trustedform.com/$CERT_ID/check_in

components:
  schemas:
    CheckInResponse:
      description: An HTTP status code generated from a Certificate URL.
      properties:
        status_code:
          type: string

  securitySchemes:
    API Key:
      scheme: basic
      description: >
        TrustedForm uses [HTTP Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) with the username `API` and your API key as the password.
        For example: `API:1f1b96c9150d8050e858c043d543bb4eadae0e6f`
      type: http
