openapi: 3.0.0
info:
  version: 1.0.0
  title: TrustedForm Ping
  termsOfService: 'https://activeprospect.com/trustedform-eula'
  description: |
    # Overview
    ActiveProspect provides TrustedForm Ping to allow customers to access certificate data with a faster response time than the TrustedForm claim process.

    # Comparison to Claim
    TrustedForm Ping does not replace the Claim process. Ping cannot be used to verify or store consent for TCPA compliance. It does not support page scanning, fingerprinting, video replay, or certificate storage.

    Please refer to the [TrustedForm Knowledge Base](https://support.activeprospect.com/hc/en-us/articles/201325449) for details on claiming a certificate.

    At present, Ping does not support masked certificates, although support is planned for the future.

    ## Ping URLs versus Certificate URLs
    In some situations, vendors won't provide a TrustedForm Certificate URL as PII can be accessed via the video replay feature.

    Specifically, in the "ping-post" lead bidding model, vendors typically don't provide PII to buyers during the "ping". They only make it available after the auction has ended and the lead has been purchased (the "post").

    To address this situation, vendors can enable a special TrustedForm script flag that issues a Ping URL in addition to the standard Certificate URL. TrustedForm Ping URLs provide a PII-stripped view of a Certificate suitable for consumption by an automated bid generator, lead vendors can pass the TrustedForm Ping URL during the "ping" step.

    Ping URLs are API-only, they cannot be viewed in a browser like a Certificate URL, and as mentioned, do not contain a video replay.

    Ping URLs begin with `https://ping.trustedform.com`

    Certificate URLs begin with `https://cert.trustedform.com`

    # Retrieving Ping Data

    A certificate's Ping data can be accessed two ways:

     - Querying a modified TrustedForm Certificate URL
     - Querying a vendor-provided TrustedForm Ping URL

    <security-definitions /> 

  contact:
    name: ActiveProspect Support Team
    email: support@activeprospect.com
    url: https://support.activeprospect.com
  x-logo:
    url: https://mrjuicebox.github.io/ActiveProspect_Full.svg
    altText: ActiveProspect logo
servers:
  - url: https://ping.trustedform.com
externalDocs:
  description: TrustedForm Knowledge Base
  url: https://support.activeprospect.com/hc/en-us/categories/200128909-TrustedForm

# tags:
#   - name: ping
#     description: Operations that can be performed against the Ping API
#   - name: cert
#     description: Operations that can be performed against the Certificate API
# x-tagGroups:
#   - name: Ping Operations
#     tags:
#       - ping
#   - name: Certificate Operations
#     tags:
#       - cert
paths:
  '/{cert_id}/ping':
    get:
      summary: Retrieve Ping Data
      description: |
        Retrieve ping data directly from a certificate.

        When a lead vendor only provides a TrustedForm Certificate URL, Ping data can be retrieved directly without a Ping URL. Append `/ping` to the certificate URL and perform an authenticated `GET`.
      tags:
        - Certificate URL Operations
      operationId: cert_ping
      parameters:
        - name: cert_id
          in: path
          description: Certificate ID
          required: true
          deprecated: false
          schema:
            type: string
      responses:
        '200':
          description: Ping Data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ping'
        '400':
          description: Malformed Certificate URL
        '401':
          description: Unauthorized
        '404':
          description: Certificate Not Found
      servers:
        - url: https://cert.trustedform.com
      security:
        - API Key: []
      x-code-samples:
        - lang: 'curl'
          source: |
            API_KEY="f3bff7c5140a10ab5ff2e628f433f0bb51d255d1a"
            CERT_ID="1f1b96c9150d8050e858c043d543bb4eadae0e6f"
            curl --user "API:$API_KEY" \
                 --request GET \
                 https://cert.trustedform.com/$CERT_ID/ping

  '/{cert_id}':
    post:
      summary: Claim a Certficate
      description: |
        Claim a Certificate, ensuring that the Ping URL matches the Certificate URL.

        In a ping-post scenario, there exists the rare possiblity that a nefarious vendor could engage in bait-and-switch: Initially sending buyers a Ping URL that indicates a high probability of conversion, and then sending the auction winner a certificate associated with a lead that has low conversion probability. To protect against this, it's important to ask TrustedForm to verify that the Ping URL used to generate the bid matches the certificate being claimed.

        Please note, this is not exhaustive documentation for claiming a certificate, it only demonstrates the Ping URL verification feature. For more documentation on claiming a certificate, please see our [Knowledge Base](https://support.activeprospect.com/hc/en-us/articles/201325449-Claiming-a-TrustedForm-certificate).
      tags:
        - Certificate URL Operations
      operationId: cert_claim
      parameters:
        - name: cert_id
          in: path
          description: Certificate ID
          required: true
          deprecated: false
          schema:
            type: string
        - name: ping_url
          in: query
          description: Ping URL
          required: false
          deprecated: false
          schema:
            type: string
      responses:
        '200':
          description: Certificate Claim Data
        '400':
          description: Malformed Certificate URL
        '401':
          description: Unauthorized
        '404':
          description: Certificate Not Found
        '412':
          description: Ping URL doesn't match this Certificate
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      detail:
                        type: string
                        enum:
                          - "the provided ping url does not match the requested certificate"
      servers:
        - url: https://cert.trustedform.com
      security:
        - API Key: []
      x-code-samples:
        - lang: 'curl'
          source: |
            API_KEY="f3bff7c5140a10ab5ff2e628f433f0bb51d255d1a"
            CERT_ID="1f1b96c9150d8050e858c043d543bb4eadae0e6f"
            PING_URL="https://ping.trustedform.com/non-matching-ping-id"
            curl --verbose \
                 --user "API:$API_KEY" \
                 --header "Accept: application/json" \
                 --request POST \
                 --data "ping_url=$PING_URL" \
                 https://cert.trustedform.com/$CERT_ID

  '/{ping_id}':
    get:
      summary: Retrieve Ping Data
      description: |
        Retrieve ping data from a Ping URL
      tags:
        - Ping URL Operations
      operationId: ping
      parameters:
        - name: ping_id
          in: path
          description: Ping ID
          required: true
          deprecated: false
          schema:
            type: string
      responses:
        '200':
          description: Ping Data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ping'
        '400':
          description: Malformed Ping URL
        '401':
          description: Unauthorized
        '404':
          description: The Certificate represented by this Ping URL was Not Found
      servers:
        - url: https://ping.trustedform.com
      security:
        - API Key: []
      x-code-samples:
        - lang: 'curl'
          source: |
            API_KEY="f3bff7c5140a10ab5ff2e628f433f0bb51d255d1a"
            PING_ID="0.2E7zgi_K8Cqvd-lr69QOr6z5f12cfxfW9sH2yEhEw2j9HX1pgaO3pTA2CKT2fiS_DuvYUwgu.jqwLEs5T_txDm2HZdSj9yw.T3ys69Gus1dGZInuu7VUIQ"
            curl --user "API:$API_KEY" \
                 --request GET \
                 https://ping.trustedform.com/$PING_ID

components:
  schemas:
    Dimension:
      description: In pixels.
      properties:
        width:
          type: integer
          format: int64
        height:
          type: integer
          format: int64

    Ping:
      type: object
      properties:
        age:
          type: integer
          format: int64
          description: |
            Lead Age, in milliseconds.

            (The time elapsed between the final recorded interaction event and the call to this API)
        created_at:
          type: string
          format: date-time
          description: |
            When the certificate was issued, in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
        time_on_page:
          type: integer
          format: int64
          description: |
            The amount of time the user spent interacting with the page, in milliseconds.

            (The time elapsed between `created_at` and the final recorded interaction event)
        client:
          type: object
          description: Information about the user's device and browser.
          properties:
            device_fingerprint:
              type: string
              description: |
                A digest (hash) of the user's device/agent configuration. Certificates with the same device fingerprint are not necessarily the same device nor the same user.

                Identically configured devices will have identical device fingerprints e.g. iOS on the same version/hardware.

                This information is suitable for determining that leads came from different devices, it is not suitable for determining that they came from the same device.
            ip:
              type: string
              description: The device's IP address.
            user_agent:
              type: string
              description: The browser's `User-Agent` header.
            dimensions:
              description: The device and browser visual display sizes.
              properties:
                screen:
                  description: The device's screen dimensions.
                  allOf:
                    - $ref: '#/components/schemas/Dimension'
                window:
                  description: The browser's screen dimensions.
                  allOf:
                    - $ref: '#/components/schemas/Dimension'
            geo:
              type: object
              description: Geographic information derived from the device's IP address.
              properties:
                city:
                  type: string
                  description: The device's city.
                country:
                  type: string
                  description: The device's country.
                postal_code:
                  type: string
                  description: The device's postal code.
                subdivisions:
                  type: array
                  description: |
                    The device location's political subdivisions.

                    States, provinces, prefectures, etc...
                  items:
                    type: string
            location:
              type: object
              description: Information about the page's location.
              properties:
                framed:
                  type: boolean
                  description: Indicates if the page that generaed the Certificate was in a frame.
                parent_url:
                  type: string
                  nullable: true
                  description: |
                    If the page was in a frame, the parent frame's URL.

                    If the parent frame is the `window`, it will be the `window`'s URL.
                url:
                  type: string
                  description: The URL of the page where the Certificate was generated.


  securitySchemes:
    API Key:
      scheme: basic
      description: >
        TrustedForm uses [HTTP Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) with the username `API` and your API key as the password.
        For example: `API:1f1b96c9150d8050e858c043d543bb4eadae0e6f`
      type: http
